console.log("Welcome");
console.log('Welcome');
console.log("Welcome");
var a = 10;
console.log("the value of a is ".concat(a));
console.log("the value of a is" + a);
console.log('the value of a is' + a);
var str;
console.log("the value of str is " + str);
str = "vishal";
console.log("the value of str is " + str);
var active = true;
console.log("the value of active is " + active);
var many;
many = 10;
console.log("the value of many is " + many);
many = "umang";
console.log("the value of many is " + many);
many = false;
console.log("the value of many is " + many);
var b = 4.5;
b = 40;
var c;
c = 20;
c = "vishal";
c = false;
console.log("value of c is" + c);
